/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dialog;

import entity.MessagesManager;
import io.AvatarManager;
import java.awt.Desktop;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.net.URI;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author hba19
 */
public class ShowCustMessageDialog extends javax.swing.JFrame {

    private JFrame parent = null;
    private String requesterID;

    /**
     * Creates new form SendCustMessageDialog
     */
    public ShowCustMessageDialog() {
        initComponents();
        this.setIconImage(AvatarManager.getAvatar());
        this.getRootPane().setDefaultButton(close);
    }

    public ShowCustMessageDialog(JFrame f, String requesterID, String requesterName, String content, String tickets, String jira) {
        initComponents();
        this.setIconImage(AvatarManager.getAvatar());
        this.getRootPane().setDefaultButton(close);
        parent = f;
        if (parent != null) {
            parent.setEnabled(false);
        }
        this.requesterID = requesterID;
        this.from_user.setText(requesterName);
        this.content.setText(content.replace(";;", "\n"));
        this.attchedticket.setText(tickets);
        this.attachedjira.setText(jira);
        this.visitticket.setEnabled(!attchedticket.getText().isEmpty());
        this.visitjira.setEnabled(!attachedjira.getText().isEmpty());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        from_user = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        content = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        attchedticket = new javax.swing.JTextField();
        attachedjira = new javax.swing.JTextField();
        close = new javax.swing.JButton();
        reply = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        visitticket = new javax.swing.JButton();
        visitjira = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Show Message");
        setIconImages(null);
        setUndecorated(true);
        setResizable(false);

        jLabel1.setText("From Agent:");

        from_user.setText("Test");
        from_user.setEnabled(false);

        jLabel2.setText("Message:");

        content.setEditable(false);
        content.setColumns(20);
        content.setRows(5);
        jScrollPane1.setViewportView(content);

        jLabel3.setText("Attached Ticket:");

        jLabel4.setText("Attached Jira:");

        attchedticket.setEditable(false);
        attchedticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attchedticketActionPerformed(evt);
            }
        });

        attachedjira.setEditable(false);

        close.setForeground(new java.awt.Color(0, 204, 102));
        close.setText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        reply.setForeground(new java.awt.Color(255, 102, 0));
        reply.setText("Reply");
        reply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replyActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(102, 102, 102));
        jLabel6.setText("You have recieved a custom message");

        visitticket.setText("Visit");
        visitticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visitticketActionPerformed(evt);
            }
        });

        visitjira.setText("Visit");
        visitjira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visitjiraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(from_user, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(reply, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(attchedticket, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(attachedjira, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(visitticket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(visitjira, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(39, 39, 39))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(from_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(attchedticket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(visitticket))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(attachedjira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(visitjira))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(close)
                    .addComponent(reply))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void replyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replyActionPerformed
        // TODO add your handling code here:
        SendCustMessageDialog sc = new SendCustMessageDialog(null, requesterID);
        sc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_replyActionPerformed

    private void attchedticketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attchedticketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_attchedticketActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_closeActionPerformed

    private void visitticketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visitticketActionPerformed
        // TODO add your handling code here:
        String url = "https://community.exoplatform.com/portal/support/";
        String tickets = attchedticket.getText();
        if (tickets == null || tickets.isEmpty()) {
            return;
        }
        if (tickets.contains("\\;")) {
            String t[] = tickets.split("\\;");
            for (String item : t) {
                try {
                    Desktop.getDesktop().browse(new URI(url + item));
                } catch (Exception f) {
                }
            }

        } else {
            try {
                Desktop.getDesktop().browse(new URI(url + tickets));
            } catch (Exception f) {
            }
        }
    }//GEN-LAST:event_visitticketActionPerformed

    private void visitjiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visitjiraActionPerformed
        // TODO add your handling code here:
        String url = "https://jira.exoplatform.org/browse/";
        String jira = attachedjira.getText();
        if (jira == null || jira.isEmpty()) {
            return;
        }
        if (jira.contains("\\;")) {
            String t[] = jira.split("\\;");
            for (String item : t) {
                try {
                    Desktop.getDesktop().browse(new URI(url + item));
                } catch (Exception f) {
                }
            }

        } else {
            try {
                Desktop.getDesktop().browse(new URI(url + jira));
            } catch (Exception f) {
            }
        }

    }//GEN-LAST:event_visitjiraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowCustMessageDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowCustMessageDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowCustMessageDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowCustMessageDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowCustMessageDialog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField attachedjira;
    private javax.swing.JTextField attchedticket;
    private javax.swing.JButton close;
    private javax.swing.JTextArea content;
    private javax.swing.JTextField from_user;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton reply;
    private javax.swing.JButton visitjira;
    private javax.swing.JButton visitticket;
    // End of variables declaration//GEN-END:variables
}
